version: "3.8"
 
services:
  mysql:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: Root@72003
      MYSQL_DATABASE: college_db
    ports:
      - 3307:3306
   
  nestjs:
    image: nest-college-erp-backend:latest # Replace this with your Docker image name
    ports:
      - 3001:3000
    depends_on:
      - mysql
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=Root@72003
      - DATABASE_NAME=college_db
      - JWT_SECRETKEY=siddhkothari

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  